WCSCoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        arrival:
            type: string
            length: '4'
        pilot:
            type: string
            length: 255
        freeSeat:
            type: integer
        takeofTime:
            type: datetime
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCSCoavBundle\Entity\Terrain
            inversedBy: departures

    oneToMany:
        flights:
            targetEntity: WCSCoavBundle\Entity\Reservation
            mappedBy: flight

    manyToOne:
        plane:
            targetEntity: WCSCoavBundle\Entity\PlaneModel
            inversedBy: planes
