WCSCoavBundle\Entity\PlaneModel:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\PlaneModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        model:
            type: string
            length: 255
        manufacturer:
            type: string
            length: 255
        cruiseSpeed:
            type: integer
        nbSeats:
            type: integer
        status:
            type: string
            length: 255
            column: Status
    lifecycleCallbacks: {  }

