services:
#    wcs_coav.example:
#        class: WCSCoavBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    app.admin.terrain:
        class: WCSCoavBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Terrain" }
        arguments:
            - ~
            - WCSCoavBundle\Entity\Terrain
            - ~